### ISSUE TITLE
Compiling CLI version

### ISSUE THREAD

**Issue by akozar** [drake7707/paintbynumbersgenerator#10]
When I'm trying to compile CLI version, **pkg** returns a message below:
`> Error! Bin file does not exist (taken from package.json 'bin' property)
  /var/www/public/paintbynumbersgenerator/src-cli/main.js`

So I changed 'bin' property to "./src-cli/main.ts". Then I got a message
`> Error! Unexpected token (19:11)
  /var/www/public/paintbynumbersgenerator/src-cli/main.ts`

How could I compile a CLI version?

**Comment by drake7707** [comment]
main.ts is a typescript file, you need to compile this to main.js. In visual studio code make sure you run the typescript compiler action, or otherwise run tsc -w in the src-cli folder. If you haven't gotten typescript installed you can do so with `npm install -g typescript.`

**Comment by akozar** [comment]
@drake7707 Thank you for responding my question! I've compile it successfully.
