### ISSUE TITLE
Vector import

### ISSUE THREAD

**Issue by hovornyan** [drake7707/paintbynumbersgenerator#3]
It's possible to import a vector image?
For example to import svg file and only numbers ad colors numbers.

Useful when you design the file in AI. With the current build, you must export the file in png and to trace it again this leed to quality loss

**Comment by drake7707** [comment]
If I understand you correctly you want to:

 1. import any svg file, created by any application
 2. add numbers to that file

That's going to be nigh on impossible to do. SVG files can be constructed any number of ways. There is no notion of a "facet" or anything, it's just a bunch of paths and/or shapes and without that metadata there is no way to be able to actually determine the label placement. The best course of action is as you describe, export it in large enough resolution to png and use that an input image. It would require a completely different approach than I'm currently using (pixel walking, etc.) to support vector images.
